[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
NODE_ENV = "production"
PORT = 3001

# Redis configuration - Railway will provide REDIS_URL automatically
# when you add Redis service to your project

# Required environment variables (add these in Railway dashboard):
# GEMINI_API_KEY = "your-gemini-api-key"
# EXA_API_KEY = "your-exa-api-key"
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_SERVICE_ROLE_KEY = "your-supabase-service-role-key"
# REDIS_URL = "redis://..." (auto-provided by Railway Redis)

# Optional:
# ENABLE_CRON = "true"
# WEBHOOK_URL = "https://your-frontend.vercel.app/api/webhooks/collector"

[healthcheck]
port = 3001
path = "/api/health"
interval = 30
timeout = 5
attempts = 3
wait = 10
initialDelay = 10

# Disable sleeping (keep service always active)
[service]
internalPort = 3001
enableSleeping = false

# Resource limits (adjust based on your Railway plan)
[resources]
memory = "512MB"
cpu = "0.5"

# Networking
[network]
port = 3001 